# Generated by Django 3.2 on 2022-01-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0005_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewsite.game'),
        ),
    ]
