# Generated by Django 3.2 on 2022-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0009_auto_20220117_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
