# Generated by Django 3.2 on 2022-01-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsite', '0010_auto_20220122_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='approved',
        ),
    ]
